### ISSUE TITLE
移植ByteTrack后跟踪效果变差

### ISSUE THREAD

**Issue by FunnyWii** [emptysoal/TensorRT-YOLOv8-ByteTrack#10]
作者您好，
同样是使用YOLOv8s模型，直接运行您的程序，和将ByteTrack程序移植到其他YOLOv8s-TensorRT的框架下，发现跟踪效果差别很大。
您的程序能够正常跟踪画面中的所有目标，
但是移植后的程序只能跟踪一部分目标。
图1是移植后的代码。
图2是您的代码。
![Screenshot from 2024-09-04 16-16-55](https://github.com/user-attachments/assets/f78094fc-5843-4fc1-b598-03efb211a3c4)
![Screenshot from 2024-09-04 16-17-51](https://github.com/user-attachments/assets/f584bfde-2865-4da7-b7eb-a9e88460fee3)
不太清楚为什么会导致这种差别

**Comment by emptysoal** [comment]
将ByteTrack程序移植到其他YOLOv8s-TensorRT的框架下，具体是什么

**Comment by FunnyWii** [comment]
> 将ByteTrack程序移植到其他YOLOv8s-TensorRT的框架下，具体是什么

使用的是https://github.com/triple-Mu/YOLOv8-TensorRT 的 detect-normal框架

**Comment by emptysoal** [comment]
哦哦，之前我也浏览过这个项目。

我还写了一个 YOLOv8 各种任务 pth -> onnx -> tensorrt 的项目，其中包括跟踪，链接就在这个项目 README 标题下方

**Comment by FunnyWii** [comment]
测试了一下，似乎是参数的问题，您对下面这三个参数以及yolo检测的score_threshold的调整有啥心得吗
`track_thresh = 0.4;
	high_thresh = 0.4;
	match_thresh = 0.5;`

**Comment by emptysoal** [comment]
bytetrack参数都保持默认，yolo的score threshold设为0.01

**Comment by FunnyWii** [comment]
> bytetrack参数都保持默认，yolo的score threshold设为0.01

bytetrack参数默认的话，跟踪效果就是我第一张图里的样子，有些目标会跟踪不到。
看到python代码里` self.det_thresh = args.track_thresh + 0.1` 有这么一行。意思是ByteTrack的track_thresh应该比yolo检测thres高0.1的样子

然后您的yolov8_trt代码里给出的置信度阈值是
`
CONF_THRESH = 0.5
IOU_THRESHOLD = 0.4`

**Comment by emptysoal** [comment]
self.det_thresh应该和检测的thres不是一回事

这个项目 yolo/include/config.h 文件里，配置是这样的：
const static float kNmsThresh = 0.45f;
const static float kConfThresh = 0.01f;

**Comment by emptysoal** [comment]
bytetrack的原理最好再看一看

**Comment by FunnyWii** [comment]
OK明白，感谢作者
