### ISSUE TITLE
随着程序运行， tracker.update 函数消耗时间也变长

### ISSUE THREAD

**Issue by FunnyWii** [emptysoal/TensorRT-YOLOv8-ByteTrack#11]
作者您好，不知道您有没有拿长视频测试过，         
在我的AGX Orin设备上，
` std::vector<STrack> output_stracks = tracker.update(objs);
`
这个函数的运行时间会随着程序运行，耗费越来越多的时间。
会从0.x ms 逐渐变成上百ms。

**Comment by FunnyWii** [comment]
```

	if (objects.size() > 0)
	{
		for (int i = 0; i < objects.size(); i++)
		{
			vector<float> tlbr_;
			tlbr_.resize(4);
			tlbr_[0] = objects[i].rect.x;
			tlbr_[1] = objects[i].rect.y;
			tlbr_[2] = objects[i].rect.x + objects[i].rect.width;
			tlbr_[3] = objects[i].rect.y + objects[i].rect.height;

			float score = objects[i].prob;
			STrack strack(STrack::tlbr_to_tlwh(tlbr_), score);
			if (score >= track_thresh)
			{
				detections.push_back(strack);
			}
			else
			{
				detections_low.push_back(strack);
			}
			
		}
	}
```

最后定位到了这里

**Comment by FunnyWii** [comment]
打印了一下`if (score >= track_thresh)`整个部分的函数耗时

能发现有一个目标的`push_back`的时间越来越长，这个您有什么头绪吗
cost 0.0050 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0020 ms
**cost 3.1600 ms**
cost 0.0040 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0020 ms
**cost 3.0400 ms**
cost 0.0680 ms
cost 0.0000 ms
cost 0.0020 ms
cost 0.0020 ms
**cost 6.1410 ms**
cost 0.0040 ms
cost 0.0000 ms
cost 0.0040 ms
cost 0.0020 ms
**cost 3.7140 ms**
cost 0.1740 ms
cost 0.0000 ms
cost 0.0040 ms
cost 0.0020 ms
cost 2.0520 ms
cost 0.0030 ms
cost 0.0000 ms
cost 0.0040 ms
cost 0.0020 ms
**cost 4.0050 ms**
cost 0.1600 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0010 ms
**cost 6.7300 ms**
cost 0.0050 ms
cost 0.0000 ms
cost 0.0040 ms
cost 0.0020 ms
**cost 3.9500 ms**
cost 0.0840 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0020 ms
**cost 4.3920 ms**
cost 0.0040 ms
cost 0.0000 ms
cost 0.0040 ms
cost 0.0020 ms
**cost 5.2440 ms**
cost 0.0050 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0020 ms
cost 1.9730 ms
cost 0.0030 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0020 ms
cost 4.1870 ms
cost 0.1500 ms
cost 0.0000 ms
cost 0.0040 ms
cost 0.0000 ms
cost 0.0020 ms
cost 6.7540 ms
cost 0.0050 ms
cost 0.0000 ms
cost 0.0070 ms
cost 0.0000 ms
cost 0.0020 ms
cost 2.1210 ms
cost 0.0030 ms
cost 0.0000 ms
cost 0.0020 ms
cost 0.0000 ms
cost 0.0020 ms
cost 2.0810 ms
cost 0.0040 ms
cost 0.0000 ms
cost 0.0020 ms
cost 0.0000 ms
cost 0.0020 ms
cost 4.3520 ms
cost 0.1140 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0000 ms
cost 0.0020 ms
cost 1.9700 ms
cost 0.0040 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0000 ms
cost 0.0020 ms
cost 6.9960 ms
cost 0.1150 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0000 ms
cost 0.0020 ms
cost 5.5520 ms
cost 0.0040 ms
cost 0.0000 ms
cost 0.0030 ms
cost 0.0000 ms
cost 0.0020 ms
cost 3.8220 ms
cost 0.0040 ms
cost 0.0000 ms
cost 0.0020 ms
cost 0.0000 ms

**Comment by emptysoal** [comment]
跟踪部分直接从官方那搬来的，去那里试试吧 https://github.com/ifzhang/ByteTrack
