### ISSUE TITLE
这个this->removed_stracks会不会带来运行过程中的内存占用持续增长

### ISSUE THREAD

**Issue by wuyuetao** [emptysoal/TensorRT-YOLOv8-ByteTrack#3]
https://github.com/emptysoal/TensorRT-YOLOv8-ByteTrack/blob/97aea00f11d125a6d854d01778ef65efb4b1cfdc/bytetrack/src/BYTETracker.cpp#L223
我看了下这个remove_stracks属于类变量，好像没看到清除机制，如果持续运行会不会带来内存占用持续增长？

**Comment by emptysoal** [comment]
栈区的，不用管，你也管不了；而且项目中只会创建一个BYTETrack实例，也就只有一个removed_tracks，根本不会有副本产生，内存上哪持续增长去

**Comment by wuyuetao** [comment]
感谢回复，我最近把你这bytetrack编译成了win动态库调用，现在定位到这个动态库内存占用在增长，我找了很久就看到这个this->remove_stracks，检查了下似乎这个类变量似乎可能无限增长，没看到有对这个类变量进行清除。可能是我自己的代码问题，我再去排查一下别的位置吧。打扰了。
