### ISSUE TITLE
目标丢失问题

### ISSUE THREAD

**Issue by strong-watermelon** [emptysoal/TensorRT-YOLOv8-ByteTrack#4]
大佬你好，我在使用您的代码过程中发现，在车辆的跟踪上，处于竖直方向上运动的车辆是可以很好的跟踪的，但是水平方向上运动的车辆是无法跟踪的，这是由于什么导致的呢，他们的检测置信度都很高的，请问您有什么思路吗。感谢！

**Comment by emptysoal** [comment]
你好，首先欢迎你对本项目的使用。

你问的这个问题，我之前也发现了，但当时只认为可能是数据集中侧面车辆的样本少导致的，就没有在意，
现在你问起来，我突然觉得可能没这么简单，于是这几天作者一直在工作之余深入研究

现在已经是解决了

解决方法：
发现丢失的目标都是非常扁的，联想到 ByteTrack 刚出来时只用于跟踪人，所以猜想可能对宽高比做了限制；
于是仔细研读了 ByteTrack  C++ 代码，确实发现了这一条件，进而解决了该问题

最后：
如果本项目对你有帮助，还希望不吝Star，对作者项目的鼓励是作者开源的最大动力，感谢！

**Comment by strong-watermelon** [comment]
谢谢大佬的解惑!已经Star，赞一个！
