### ISSUE TITLE
图像裁剪之后，检测不出任何框。

### ISSUE THREAD

**Issue by lkw052715** [emptysoal/TensorRT-YOLOv8-ByteTrack#6]
code:
img = frame(cv::Rect(100, 100,500, 500));
std::vector<Detection> res = detecter.inference(img);
这样操作 res.size()始终等于0，但是在tensorrt-yolov8 里面是正常的，看到博主说改写了预处理，是和这个有关吗，感谢期待您的回复。

**Comment by emptysoal** [comment]
原视频分辨率跟踪效果截图
![result_src](https://github.com/emptysoal/TensorRT-YOLOv8-ByteTrack/assets/57931586/ac51a6e4-55f9-440d-82f0-15edc4ae331e)
原视频帧先裁剪后，再跟踪效果截图
![result_crop](https://github.com/emptysoal/TensorRT-YOLOv8-ByteTrack/assets/57931586/92709a33-cba4-44ae-bf2e-87ec6873aee4)
所以代码没有问题

**Comment by lkw052715** [comment]
是的，把裁剪后图片clone一份，就能正常运行，感谢回复
