### ISSUE TITLE
关于preporcess.cu的代码问题

### ISSUE THREAD

**Issue by mawenjie1111** [emptysoal/TensorRT-YOLOv8-ByteTrack#7]
请问大佬，preprocess.cu中的cuda代码在编译是会报语法错误如何解决？
如下图：
![image](https://github.com/emptysoal/TensorRT-YOLOv8-ByteTrack/assets/90663707/7ac53cbe-ca5f-47f1-a287-9f177a7d7e04)

我是在win10上进行编译部署，使用cmake+vs 2022
在编译时，我将该cu编辑为CUDA类型，但是编译总是会报这种错误，目前来看代码不存在语法错误，可能由于其他原因导致的编译问题，反映为了语法报错，大佬有什么思路吗？

**Comment by emptysoal** [comment]
我从来没在Windows上编译过，这个确实是不清楚，可能帮不到什么

**Comment by mawenjie1111** [comment]
感谢你的回复，我已经解决了这个问题并通过了编译，但是我在运行时发现了一个问题，我使用了自己的yolo训练的engine，并且类别只有5类，但是在程序运行的时候会出现class id大于5的问题，并且会有14个class id。所以在这个程序中，是如何定义分类类别数的？

**Comment by mawenjie1111** [comment]
这是我的运行程序的结果
![image](https://github.com/emptysoal/TensorRT-YOLOv8-ByteTrack/assets/90663707/af1db4e8-120f-4841-bef8-dbfb61f4bd7f)
可以看到，class id出现很奇怪的数字

**Comment by emptysoal** [comment]
tensorrtx-yolov8/include/config.h这个文件中的第6行，const static int kNumClass = 80; 设定了转tensorrt的类别

我还有一版 yolov8+tensorrt 实现各种任务的项目 https://github.com/emptysoal/TensorRT-YOLOv8，包括检测、关键点、分割、跟踪，基于pth->onnx->engine的转换方式，当前项目如果你实在跑不通，可以用这一版

**Comment by emptysoal** [comment]
tensorrtx-yolov8/include/config.h这个文件中的第6行，const static int kNumClass = 80; 设定了转tensorrt的类别

我还有一版 yolov8+tensorrt 实现各种任务的项目 https://github.com/emptysoal/TensorRT-YOLOv8  ，包括检测、关键点、分割、跟踪，基于pth->onnx->engine的转换方式，当前项目如果你实在跑不通，可以用这一版
