### ISSUE TITLE
请教一下卡尔曼滤波是不是没有用起来呀

### ISSUE THREAD

**Issue by jedi007** [emptysoal/TensorRT-YOLOv8-ByteTrack#8]
我看代码里面的 gating_distance 应该是光做了声明和定义，而并没有使用。是不是说博主的代码里没有考虑卡尔曼滤波的计算呀

**Comment by emptysoal** [comment]
![123](https://github.com/user-attachments/assets/aaea4e44-3d68-43f3-9315-ee22581c1ff5)

**Comment by jedi007** [comment]
谢谢大佬回复。
又仔细研读了代码，kalman_filter的计算结果确实是用上了的。是在这个：static_tlwh() 里面使用了卡尔曼滤波的结果对位置进行更新。

但是gating_distance确实没有用上，看其他的代码里面，这个应该是用在对ReID的特征距离进行过滤的。
